Add a parallel iterator of matching positions
rayon-rs/rayon pull request #788
Opened 2020-08-17 00:51 UTC by cuviper

This is the plural of the `position` methods, where `positions` finds
_all_ matching items and returns their indices in a new iterator. This
matches the API of `Itertools::positions`, but in parallel.

2020-09-15 19:29 UTC, nikomatsakis requested changes
The code looks right, but I don't really see any tests with non-trivial predicates, can we add some?

2020-09-15 19:47 UTC, cuviper commented
@nikomatsakis I don't have non-trivial unit tests, but I think the doc-tests should suffice.

2020-09-29 20:27 UTC, nikomatsakis commented
bors r+

2020-09-29 20:27 UTC, nikomatsakis commented
Agreed!

2020-09-29 20:41 UTC, merged