Fix clippy lints
rayon-rs/rayon pull request #960
Opened 2022-07-12 02:53 UTC by JoeyBF

I went through the codebase and fixed all the lints. I don't know if some of these were optimizations but the few benches I ran showed no regressions

2022-07-12 05:22 UTC, adamreichold commented
Rayon currently has an MSRV of 1.36.0 so that e.g. `mem::take` cannot be used in the code base as it was stabilised only in 1.40.0.

2022-07-12 05:57 UTC, JoeyBF commented
Good point, I made sure it compiles with 1.36. I left some `#[allow(...)]` for when the MSRV gets raised in the future

2022-07-15 19:43 UTC, cuviper requested changes
I went ahead and fixed a few more in rayon-demo -- will push in a moment.

2022-07-16 05:00 UTC, JoeyBF commented on src/iter/mod.rs
> +    fn is_empty(&self) -> bool {
Good point, I added an `allow` and a comment about that

2022-07-18 19:36 UTC, cuviper commented
Thanks!

bors r+

2022-07-18 19:44 UTC, merged