Fix typos
rayon-rs/rayon pull request #978
Opened 2022-09-21 14:13 UTC by kianmeng

Found via `codespell -L crate,fromt`

2022-09-22 23:24 UTC, cuviper requested changes

2022-09-22 23:24 UTC, cuviper commented on rayon-core/src/lib.rs
> +    /// steal from the bottom of other worker's dequeues, regardless of
This is not a typo -- just the plural of "deque" that you left on the line above.

2022-09-22 23:24 UTC, cuviper commented on rayon-core/src/registry.rs
> +            // dequeues, and finally to injected jobs from the
Ditto, not a typo.

2022-09-22 23:24 UTC, cuviper commented on src/slice/mergesort.rs
> +    // merge chunks from `v` into `buf`, and vice-versa.
This should just be two words.

```suggestion
    // merge chunks from `v` into `buf`, and vice versa.
```

2022-09-22 23:26 UTC, cuviper commented on rayon-core/src/lib.rs
> +    /// steal from the bottom of other worker's dequeues, regardless of
The plural possessive should be updated though...
```suggestion
    /// steal from the bottom of other workers' deques, regardless of
```

2022-09-24 19:26 UTC, cuviper commented
bors r+

2022-09-24 19:32 UTC, merged

2022-09-25 08:02 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: